### ISSUE TITLE
Issues when running default workflow a second time

### ISSUE THREAD

**Issue by OZARIN** [kogakure/gulp-tutorial#12]
When running the default gulp task, there are no problems - but there is a warning:

```
Node#before is deprecated. Use Node#raws.before
```

Gulp continues watching for changes and the site seems to function normally.

If I cancel and run the same default gulp task again, there are multiple errors stating file/directory doesn't exist...

```
[16:38:16] 'images' errored after 850 ms
[16:38:16] Error: ENOENT: no such file or directory, open '/Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png'
```

and...

```
[16:38:16] 'build' errored after 919 ms
[16:38:16] Error in plugin 'run-sequence(images)'
Message:
    ENOENT: no such file or directory, open '/Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: /Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png
Stack:
Error: ENOENT: no such file or directory, open '/Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png'
Node#before is deprecated. Use Node#raws.before
```

Gulp then stops watching for changes and the localhost is unreachable.

However, this works normally if I delete the build folder and run gulp again.

Can you please advise?

**Comment by OZARIN** [comment]
Tried updating the npm packages. My errors are slightly different when trying to run gulp when a build folder exists...

```
[22:45:10] 'images' errored after 828 ms
[22:45:10] Error: ENOENT: no such file or directory, chmod '/Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png'
[22:45:10] 'build' errored after 891 ms
[22:45:10] Error in plugin 'run-sequence(images)'
Message:
    ENOENT: no such file or directory, chmod '/Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png'
Details:
    errno: -2
    code: ENOENT
    syscall: chmod
    path: /Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png
Stack:
Error: ENOENT: no such file or directory, chmod '/Users/OZARIN/Downloads/gulp-tutorial-master-2/build/assets/images/sprites/icon/twitter.png'
Node#before is deprecated. Use Node#raws.before
[22:45:10] Finished 'styles' after 1.47 s
[22:45:10] Bundled head.js in 1.43 s
      status  No changes detected. Skipping compile.

```

Seems to have deleted the folder: build/assets/images. 

After...

**Comment by OZARIN** [comment]
Using the process of elimination, it appears to be an issue with deleting and building in parallel?

Anyhow, I compared the development/build function with the production/build function and noticed the 'jekyll' function was missing from the former...

```
gulp.task('build', function(callback) {
  runSequence('delete', 'jekyll',
  [
    'jekyll',
    'styles',
    'scripts',
    'images',
    'copy:fonts'
  ],
  'base64',
  callback);
});
```
_(it appears as jekyll:production in build:production)_

I added it here and no longer experience the problem when running gulp without deleting the build folder.

Maybe it's just blind luck and I'm secretly causing more harm than good? But would appreciate your feedback nonetheless. This is a really great workflow - thanks!

**Comment by kogakure** [comment]
Unfortunately I couldn’t reproduce the problem … but I got different problems with Jekyll and Liquid, when running it on my new computer. I’m not sure, what exactly the problem is, but the example you posted runs `jekyll` twice now. Once in sequence after `delete` and once in parallel inside the `[]`. This seems wrong to me.

My guess is, as the image tasks fails because it can’t create a folder, that the `del` task might not  be finished or not getting a callback. I might not having this because of a faster computer or something.

Try changing the `del` task like this:

```js
gulp.task('delete', function(callback) {
  del(config.src);
  callback();
}
```

I found another possible solution on [Stackoverflow](https://stackoverflow.com/a/32771014/331361), by returning a Promise:

```js
gulp.task('delete', function() {
  return del(config.src);
}
```

Nevertheless, as I can’t test this, I’ll push an update of my changes including the Stackoverflow solution and a Jekyll update.

**Comment by kogakure** [comment]
@OZARIN: I opened a pull request (#13), could you test if my changes helped with your problem?

P.S. If you’re interested in my current Gulp task for one of my websites, you can have a look here: https://github.com/kogakure/website-hugo-kogakure.de/blob/master/gulpfile.babel.js

**Comment by OZARIN** [comment]
Hey @kogakure, you're right about repeating the Jekyll function, it's less than ideal.

Thanks for looking into this. I'll test your changes tonight, and will check out your latest workflow - thanks for the link!

**Comment by OZARIN** [comment]
Can confirm this fixes the issue! Thanks for your time, @kogakure.
