### ISSUE TITLE
emit('end') doesn't actually end the stream, it just says "I'm done"

### ISSUE THREAD

**Issue by jpeg729** [kogakure/gulp-tutorial#4]
https://github.com/kogakure/gulp-tutorial/blob/master/gulp/util/handleErrors.js#L14

Calling this.end() looks to be a better option, but I'm not an expert.
http://www.bennadel.com/blog/2692-you-have-to-explicitly-end-streams-after-pipes-break-in-node-js.htm

**Comment by kogakure** [comment]
Feel free to submit a pull request to improve the code.
